/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VideoSettings {
    playbackSpeed: number;
    volume: number;
    isMuted: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AppEntry {
    id: string;
    url: string;
    name: string;
    position: [bigint, bigint];
}
export interface Settings {
    clockFormat: ClockFormat;
    particleIntensity: ParticleIntensity;
    accentColor: AccentColor;
    iconSize: IconSize;
    wallpaperUrl: string;
    uiTransparency: UITransparency;
    gridOverlay: GridOverlay;
    fontSize: FontSize;
    desktopLabel: string;
    scanlineEffect: ScanlineEffect;
    taskbarHeight: TaskbarHeight;
    windowBorderGlow: WindowBorderGlow;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AccentColor {
    magenta = "magenta",
    cyan = "cyan",
    green = "green"
}
export enum ClockFormat {
    hour12 = "hour12",
    hour24 = "hour24"
}
export enum FontSize {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum ParticleIntensity {
    low = "low",
    off = "off",
    high = "high",
    medium = "medium"
}
export enum ScanlineEffect {
    on = "on",
    off = "off"
}
export enum TaskbarHeight {
    normal = "normal",
    tall = "tall",
    compact = "compact"
}
export enum UITransparency {
    low = "low",
    high = "high",
    none = "none",
    medium = "medium"
}
export enum WindowBorderGlow {
    intense = "intense",
    none = "none",
    subtle = "subtle"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addApp(id: string, name: string, url: string): Promise<void>;
    doesFileExist(directoryId: string, fileName: string): Promise<boolean>;
    getApp(id: string): Promise<AppEntry>;
    getSettings(): Promise<Settings>;
    getVideoSettings(): Promise<VideoSettings>;
    saveSettings(newSettings: Settings): Promise<void>;
    updateVideoSettings(newVideoSettings: VideoSettings): Promise<void>;
}
import type { AccentColor as _AccentColor, ClockFormat as _ClockFormat, FontSize as _FontSize, GridOverlay as _GridOverlay, IconSize as _IconSize, ParticleIntensity as _ParticleIntensity, ScanlineEffect as _ScanlineEffect, Settings as _Settings, TaskbarHeight as _TaskbarHeight, UITransparency as _UITransparency, WindowBorderGlow as _WindowBorderGlow, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addApp(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addApp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addApp(arg0, arg1, arg2);
            return result;
        }
    }
    async doesFileExist(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.doesFileExist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.doesFileExist(arg0, arg1);
            return result;
        }
    }
    async getApp(arg0: string): Promise<AppEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getApp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApp(arg0);
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_Settings_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_Settings_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoSettings(): Promise<VideoSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoSettings();
            return result;
        }
    }
    async saveSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(to_candid_Settings_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(to_candid_Settings_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVideoSettings(arg0: VideoSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoSettings(arg0);
            return result;
        }
    }
}
function from_candid_AccentColor_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccentColor): AccentColor {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ClockFormat_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClockFormat): ClockFormat {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FontSize_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FontSize): FontSize {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_GridOverlay_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GridOverlay): GridOverlay {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_IconSize_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IconSize): IconSize {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ParticleIntensity_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParticleIntensity): ParticleIntensity {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ScanlineEffect_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanlineEffect): ScanlineEffect {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Settings_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settings): Settings {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TaskbarHeight_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskbarHeight): TaskbarHeight {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UITransparency_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UITransparency): UITransparency {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WindowBorderGlow_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WindowBorderGlow): WindowBorderGlow {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clockFormat: _ClockFormat;
    particleIntensity: _ParticleIntensity;
    accentColor: _AccentColor;
    iconSize: _IconSize;
    wallpaperUrl: string;
    uiTransparency: _UITransparency;
    gridOverlay: _GridOverlay;
    fontSize: _FontSize;
    desktopLabel: string;
    scanlineEffect: _ScanlineEffect;
    taskbarHeight: _TaskbarHeight;
    windowBorderGlow: _WindowBorderGlow;
}): {
    clockFormat: ClockFormat;
    particleIntensity: ParticleIntensity;
    accentColor: AccentColor;
    iconSize: IconSize;
    wallpaperUrl: string;
    uiTransparency: UITransparency;
    gridOverlay: GridOverlay;
    fontSize: FontSize;
    desktopLabel: string;
    scanlineEffect: ScanlineEffect;
    taskbarHeight: TaskbarHeight;
    windowBorderGlow: WindowBorderGlow;
} {
    return {
        clockFormat: from_candid_ClockFormat_n10(_uploadFile, _downloadFile, value.clockFormat),
        particleIntensity: from_candid_ParticleIntensity_n12(_uploadFile, _downloadFile, value.particleIntensity),
        accentColor: from_candid_AccentColor_n14(_uploadFile, _downloadFile, value.accentColor),
        iconSize: from_candid_IconSize_n16(_uploadFile, _downloadFile, value.iconSize),
        wallpaperUrl: value.wallpaperUrl,
        uiTransparency: from_candid_UITransparency_n18(_uploadFile, _downloadFile, value.uiTransparency),
        gridOverlay: from_candid_GridOverlay_n20(_uploadFile, _downloadFile, value.gridOverlay),
        fontSize: from_candid_FontSize_n22(_uploadFile, _downloadFile, value.fontSize),
        desktopLabel: value.desktopLabel,
        scanlineEffect: from_candid_ScanlineEffect_n23(_uploadFile, _downloadFile, value.scanlineEffect),
        taskbarHeight: from_candid_TaskbarHeight_n24(_uploadFile, _downloadFile, value.taskbarHeight),
        windowBorderGlow: from_candid_WindowBorderGlow_n26(_uploadFile, _downloadFile, value.windowBorderGlow)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hour12: null;
} | {
    hour24: null;
}): ClockFormat {
    return "hour12" in value ? ClockFormat.hour12 : "hour24" in value ? ClockFormat.hour24 : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    off: null;
} | {
    high: null;
} | {
    medium: null;
}): ParticleIntensity {
    return "low" in value ? ParticleIntensity.low : "off" in value ? ParticleIntensity.off : "high" in value ? ParticleIntensity.high : "medium" in value ? ParticleIntensity.medium : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    magenta: null;
} | {
    cyan: null;
} | {
    green: null;
}): AccentColor {
    return "magenta" in value ? AccentColor.magenta : "cyan" in value ? AccentColor.cyan : "green" in value ? AccentColor.green : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): FontSize {
    return "large" in value ? FontSize.large : "small" in value ? FontSize.small : "medium" in value ? FontSize.medium : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
}): UITransparency {
    return "low" in value ? UITransparency.low : "high" in value ? UITransparency.high : "none" in value ? UITransparency.none : "medium" in value ? UITransparency.medium : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    on: null;
} | {
    off: null;
}): ScanlineEffect {
    return "on" in value ? ScanlineEffect.on : "off" in value ? ScanlineEffect.off : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    tall: null;
} | {
    compact: null;
}): TaskbarHeight {
    return "normal" in value ? TaskbarHeight.normal : "tall" in value ? TaskbarHeight.tall : "compact" in value ? TaskbarHeight.compact : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intense: null;
} | {
    none: null;
} | {
    subtle: null;
}): WindowBorderGlow {
    return "intense" in value ? WindowBorderGlow.intense : "none" in value ? WindowBorderGlow.none : "subtle" in value ? WindowBorderGlow.subtle : value;
}
function to_candid_AccentColor_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccentColor): _AccentColor {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_ClockFormat_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClockFormat): _ClockFormat {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_FontSize_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FontSize): _FontSize {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_GridOverlay_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GridOverlay): _GridOverlay {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_IconSize_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IconSize): _IconSize {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ParticleIntensity_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParticleIntensity): _ParticleIntensity {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ScanlineEffect_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanlineEffect): _ScanlineEffect {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Settings_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Settings): _Settings {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_TaskbarHeight_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskbarHeight): _TaskbarHeight {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UITransparency_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UITransparency): _UITransparency {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_WindowBorderGlow_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WindowBorderGlow): _WindowBorderGlow {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clockFormat: ClockFormat;
    particleIntensity: ParticleIntensity;
    accentColor: AccentColor;
    iconSize: IconSize;
    wallpaperUrl: string;
    uiTransparency: UITransparency;
    gridOverlay: GridOverlay;
    fontSize: FontSize;
    desktopLabel: string;
    scanlineEffect: ScanlineEffect;
    taskbarHeight: TaskbarHeight;
    windowBorderGlow: WindowBorderGlow;
}): {
    clockFormat: _ClockFormat;
    particleIntensity: _ParticleIntensity;
    accentColor: _AccentColor;
    iconSize: _IconSize;
    wallpaperUrl: string;
    uiTransparency: _UITransparency;
    gridOverlay: _GridOverlay;
    fontSize: _FontSize;
    desktopLabel: string;
    scanlineEffect: _ScanlineEffect;
    taskbarHeight: _TaskbarHeight;
    windowBorderGlow: _WindowBorderGlow;
} {
    return {
        clockFormat: to_candid_ClockFormat_n30(_uploadFile, _downloadFile, value.clockFormat),
        particleIntensity: to_candid_ParticleIntensity_n32(_uploadFile, _downloadFile, value.particleIntensity),
        accentColor: to_candid_AccentColor_n34(_uploadFile, _downloadFile, value.accentColor),
        iconSize: to_candid_IconSize_n36(_uploadFile, _downloadFile, value.iconSize),
        wallpaperUrl: value.wallpaperUrl,
        uiTransparency: to_candid_UITransparency_n38(_uploadFile, _downloadFile, value.uiTransparency),
        gridOverlay: to_candid_GridOverlay_n40(_uploadFile, _downloadFile, value.gridOverlay),
        fontSize: to_candid_FontSize_n42(_uploadFile, _downloadFile, value.fontSize),
        desktopLabel: value.desktopLabel,
        scanlineEffect: to_candid_ScanlineEffect_n43(_uploadFile, _downloadFile, value.scanlineEffect),
        taskbarHeight: to_candid_TaskbarHeight_n44(_uploadFile, _downloadFile, value.taskbarHeight),
        windowBorderGlow: to_candid_WindowBorderGlow_n46(_uploadFile, _downloadFile, value.windowBorderGlow)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClockFormat): {
    hour12: null;
} | {
    hour24: null;
} {
    return value == ClockFormat.hour12 ? {
        hour12: null
    } : value == ClockFormat.hour24 ? {
        hour24: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParticleIntensity): {
    low: null;
} | {
    off: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == ParticleIntensity.low ? {
        low: null
    } : value == ParticleIntensity.off ? {
        off: null
    } : value == ParticleIntensity.high ? {
        high: null
    } : value == ParticleIntensity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccentColor): {
    magenta: null;
} | {
    cyan: null;
} | {
    green: null;
} {
    return value == AccentColor.magenta ? {
        magenta: null
    } : value == AccentColor.cyan ? {
        cyan: null
    } : value == AccentColor.green ? {
        green: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FontSize): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == FontSize.large ? {
        large: null
    } : value == FontSize.small ? {
        small: null
    } : value == FontSize.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UITransparency): {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
} {
    return value == UITransparency.low ? {
        low: null
    } : value == UITransparency.high ? {
        high: null
    } : value == UITransparency.none ? {
        none: null
    } : value == UITransparency.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanlineEffect): {
    on: null;
} | {
    off: null;
} {
    return value == ScanlineEffect.on ? {
        on: null
    } : value == ScanlineEffect.off ? {
        off: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskbarHeight): {
    normal: null;
} | {
    tall: null;
} | {
    compact: null;
} {
    return value == TaskbarHeight.normal ? {
        normal: null
    } : value == TaskbarHeight.tall ? {
        tall: null
    } : value == TaskbarHeight.compact ? {
        compact: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WindowBorderGlow): {
    intense: null;
} | {
    none: null;
} | {
    subtle: null;
} {
    return value == WindowBorderGlow.intense ? {
        intense: null
    } : value == WindowBorderGlow.none ? {
        none: null
    } : value == WindowBorderGlow.subtle ? {
        subtle: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
