/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccentColor = { 'magenta' : null } |
  { 'cyan' : null } |
  { 'green' : null };
export interface AppEntry {
  'id' : string,
  'url' : string,
  'name' : string,
  'position' : [bigint, bigint],
}
export type ClockFormat = { 'hour12' : null } |
  { 'hour24' : null };
export type FontSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export type GridOverlay = { 'on' : null } |
  { 'off' : null };
export type IconSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export type ParticleIntensity = { 'low' : null } |
  { 'off' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type ScanlineEffect = { 'on' : null } |
  { 'off' : null };
export interface Settings {
  'clockFormat' : ClockFormat,
  'particleIntensity' : ParticleIntensity,
  'accentColor' : AccentColor,
  'iconSize' : IconSize,
  'wallpaperUrl' : string,
  'uiTransparency' : UITransparency,
  'gridOverlay' : GridOverlay,
  'fontSize' : FontSize,
  'desktopLabel' : string,
  'scanlineEffect' : ScanlineEffect,
  'taskbarHeight' : TaskbarHeight,
  'windowBorderGlow' : WindowBorderGlow,
}
export type TaskbarHeight = { 'normal' : null } |
  { 'tall' : null } |
  { 'compact' : null };
export type UITransparency = { 'low' : null } |
  { 'high' : null } |
  { 'none' : null } |
  { 'medium' : null };
export interface VideoSettings {
  'playbackSpeed' : number,
  'volume' : number,
  'isMuted' : boolean,
}
export type WindowBorderGlow = { 'intense' : null } |
  { 'none' : null } |
  { 'subtle' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addApp' : ActorMethod<[string, string, string], undefined>,
  'doesFileExist' : ActorMethod<[string, string], boolean>,
  'getApp' : ActorMethod<[string], AppEntry>,
  'getSettings' : ActorMethod<[], Settings>,
  'getVideoSettings' : ActorMethod<[], VideoSettings>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
  'updateVideoSettings' : ActorMethod<[VideoSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];