/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AppEntry = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'position' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const ClockFormat = IDL.Variant({
  'hour12' : IDL.Null,
  'hour24' : IDL.Null,
});
export const ParticleIntensity = IDL.Variant({
  'low' : IDL.Null,
  'off' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const AccentColor = IDL.Variant({
  'magenta' : IDL.Null,
  'cyan' : IDL.Null,
  'green' : IDL.Null,
});
export const IconSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const UITransparency = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'none' : IDL.Null,
  'medium' : IDL.Null,
});
export const GridOverlay = IDL.Variant({ 'on' : IDL.Null, 'off' : IDL.Null });
export const FontSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const ScanlineEffect = IDL.Variant({
  'on' : IDL.Null,
  'off' : IDL.Null,
});
export const TaskbarHeight = IDL.Variant({
  'normal' : IDL.Null,
  'tall' : IDL.Null,
  'compact' : IDL.Null,
});
export const WindowBorderGlow = IDL.Variant({
  'intense' : IDL.Null,
  'none' : IDL.Null,
  'subtle' : IDL.Null,
});
export const Settings = IDL.Record({
  'clockFormat' : ClockFormat,
  'particleIntensity' : ParticleIntensity,
  'accentColor' : AccentColor,
  'iconSize' : IconSize,
  'wallpaperUrl' : IDL.Text,
  'uiTransparency' : UITransparency,
  'gridOverlay' : GridOverlay,
  'fontSize' : FontSize,
  'desktopLabel' : IDL.Text,
  'scanlineEffect' : ScanlineEffect,
  'taskbarHeight' : TaskbarHeight,
  'windowBorderGlow' : WindowBorderGlow,
});
export const VideoSettings = IDL.Record({
  'playbackSpeed' : IDL.Float64,
  'volume' : IDL.Nat8,
  'isMuted' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addApp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'doesFileExist' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getApp' : IDL.Func([IDL.Text], [AppEntry], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getVideoSettings' : IDL.Func([], [VideoSettings], ['query']),
  'saveSettings' : IDL.Func([Settings], [], []),
  'updateVideoSettings' : IDL.Func([VideoSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AppEntry = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'position' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const ClockFormat = IDL.Variant({ 'hour12' : IDL.Null, 'hour24' : IDL.Null });
  const ParticleIntensity = IDL.Variant({
    'low' : IDL.Null,
    'off' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AccentColor = IDL.Variant({
    'magenta' : IDL.Null,
    'cyan' : IDL.Null,
    'green' : IDL.Null,
  });
  const IconSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UITransparency = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'none' : IDL.Null,
    'medium' : IDL.Null,
  });
  const GridOverlay = IDL.Variant({ 'on' : IDL.Null, 'off' : IDL.Null });
  const FontSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ScanlineEffect = IDL.Variant({ 'on' : IDL.Null, 'off' : IDL.Null });
  const TaskbarHeight = IDL.Variant({
    'normal' : IDL.Null,
    'tall' : IDL.Null,
    'compact' : IDL.Null,
  });
  const WindowBorderGlow = IDL.Variant({
    'intense' : IDL.Null,
    'none' : IDL.Null,
    'subtle' : IDL.Null,
  });
  const Settings = IDL.Record({
    'clockFormat' : ClockFormat,
    'particleIntensity' : ParticleIntensity,
    'accentColor' : AccentColor,
    'iconSize' : IconSize,
    'wallpaperUrl' : IDL.Text,
    'uiTransparency' : UITransparency,
    'gridOverlay' : GridOverlay,
    'fontSize' : FontSize,
    'desktopLabel' : IDL.Text,
    'scanlineEffect' : ScanlineEffect,
    'taskbarHeight' : TaskbarHeight,
    'windowBorderGlow' : WindowBorderGlow,
  });
  const VideoSettings = IDL.Record({
    'playbackSpeed' : IDL.Float64,
    'volume' : IDL.Nat8,
    'isMuted' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addApp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'doesFileExist' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getApp' : IDL.Func([IDL.Text], [AppEntry], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getVideoSettings' : IDL.Func([], [VideoSettings], ['query']),
    'saveSettings' : IDL.Func([Settings], [], []),
    'updateVideoSettings' : IDL.Func([VideoSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };